( DEFINE ( DOMAIN DRIVERLOG )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	LOCATION - OBJECT
	LOCATABLE - OBJECT
	DRIVER - LOCATABLE
	TRUCK - LOCATABLE
	OBJ - LOCATABLE
)
( :PREDICATES
	( AT ?LOCATABLE0 - LOCATABLE ?LOCATION1 - LOCATION )
	( IN ?OBJ0 - OBJ ?TRUCK1 - TRUCK )
	( DRIVING ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK )
	( LINK ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( PATH ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( EMPTY ?TRUCK0 - TRUCK )
	( EMPTYSTACK )
	( STACK1 )
	( STACK2 )
	( ACTIVE-LOAD-TRUCK ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
	( ACTIVE-UNLOAD-TRUCK ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
	( ACTIVE-BOARD-TRUCK ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
	( ACTIVE-DISEMBARK-TRUCK ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
	( ACTIVE-DRIVE-TRUCK ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?DRIVER3 - DRIVER )
	( ACTIVE-WALK ?DRIVER0 - DRIVER ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( COUNT0-AT ?LOCATABLE0 - LOCATABLE ?LOCATION1 - LOCATION )
	( COUNT1-AT ?LOCATABLE0 - LOCATABLE ?LOCATION1 - LOCATION )
	( COUNT2-AT ?LOCATABLE0 - LOCATABLE ?LOCATION1 - LOCATION )
	( COUNT0-DRIVING ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK )
	( COUNT1-DRIVING ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK )
	( COUNT2-DRIVING ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION START-LOAD-TRUCK
  :PARAMETERS ( ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?OBJ0 ?LOCATION2 )
		( AT ?TRUCK1 ?LOCATION2 )
		( NOT ( ACTIVE-LOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 ) )
		( NOT ( STACK2 ) )
		( COUNT0-AT ?OBJ0 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?OBJ0 ?LOCATION2 ) )
		( ACTIVE-LOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 )
		( WHEN
			( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT0-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 20000 )
	)
)
( :ACTION END-LOAD-TRUCK
  :PARAMETERS ( ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK1 ?LOCATION2 )
		( ACTIVE-LOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( IN ?OBJ0 ?TRUCK1 )
		( NOT ( ACTIVE-LOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 ) )
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT2-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-UNLOAD-TRUCK
  :PARAMETERS ( ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( IN ?OBJ0 ?TRUCK1 )
		( AT ?TRUCK1 ?LOCATION2 )
		( NOT ( ACTIVE-UNLOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 ) )
		( NOT ( STACK2 ) )
	)
  :EFFECT
	( AND
		( NOT ( IN ?OBJ0 ?TRUCK1 ) )
		( ACTIVE-UNLOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 )
		( WHEN
			( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT0-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 20000 )
	)
)
( :ACTION END-UNLOAD-TRUCK
  :PARAMETERS ( ?OBJ0 - OBJ ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK1 ?LOCATION2 )
		( ACTIVE-UNLOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( AT ?OBJ0 ?LOCATION2 )
		( NOT ( ACTIVE-UNLOAD-TRUCK ?OBJ0 ?TRUCK1 ?LOCATION2 ) )
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT2-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-BOARD-TRUCK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?DRIVER0 ?LOCATION2 )
		( EMPTY ?TRUCK1 )
		( AT ?TRUCK1 ?LOCATION2 )
		( NOT ( ACTIVE-BOARD-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 ) )
		( NOT ( STACK2 ) )
		( COUNT0-AT ?DRIVER0 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?DRIVER0 ?LOCATION2 ) )
		( NOT ( EMPTY ?TRUCK1 ) )
		( ACTIVE-BOARD-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 )
		( WHEN
			( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT0-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 10000 )
	)
)
( :ACTION END-BOARD-TRUCK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK1 ?LOCATION2 )
		( ACTIVE-BOARD-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( DRIVING ?DRIVER0 ?TRUCK1 )
		( NOT ( ACTIVE-BOARD-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 ) )
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT2-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-DISEMBARK-TRUCK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( DRIVING ?DRIVER0 ?TRUCK1 )
		( AT ?TRUCK1 ?LOCATION2 )
		( NOT ( ACTIVE-DISEMBARK-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 ) )
		( NOT ( STACK2 ) )
		( COUNT0-DRIVING ?DRIVER0 ?TRUCK1 )
	)
  :EFFECT
	( AND
		( NOT ( DRIVING ?DRIVER0 ?TRUCK1 ) )
		( ACTIVE-DISEMBARK-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 )
		( WHEN
			( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT0-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 10000 )
	)
)
( :ACTION END-DISEMBARK-TRUCK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?TRUCK1 ?LOCATION2 )
		( ACTIVE-DISEMBARK-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( AT ?DRIVER0 ?LOCATION2 )
		( EMPTY ?TRUCK1 )
		( NOT ( ACTIVE-DISEMBARK-TRUCK ?DRIVER0 ?TRUCK1 ?LOCATION2 ) )
		( WHEN
			( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT1-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT0-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( COUNT2-AT ?TRUCK1 ?LOCATION2 )
			( AND
				( NOT ( COUNT2-AT ?TRUCK1 ?LOCATION2 ) )
				( COUNT1-AT ?TRUCK1 ?LOCATION2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-DRIVE-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?DRIVER3 - DRIVER )
  :PRECONDITION
	( AND
		( AT ?TRUCK0 ?LOCATION1 )
		( LINK ?LOCATION1 ?LOCATION2 )
		( DRIVING ?DRIVER3 ?TRUCK0 )
		( NOT ( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?DRIVER3 ) )
		( NOT ( STACK2 ) )
		( COUNT0-AT ?TRUCK0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?TRUCK0 ?LOCATION1 ) )
		( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?DRIVER3 )
		( WHEN
			( COUNT0-DRIVING ?DRIVER3 ?TRUCK0 )
			( AND
				( NOT ( COUNT0-DRIVING ?DRIVER3 ?TRUCK0 ) )
				( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 )
			)
		)
		( WHEN
			( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 )
			( AND
				( NOT ( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 ) )
				( COUNT2-DRIVING ?DRIVER3 ?TRUCK0 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 100000 )
	)
)
( :ACTION END-DRIVE-TRUCK
  :PARAMETERS ( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?DRIVER3 - DRIVER )
  :PRECONDITION
	( AND
		( DRIVING ?DRIVER3 ?TRUCK0 )
		( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?DRIVER3 )
	)
  :EFFECT
	( AND
		( AT ?TRUCK0 ?LOCATION2 )
		( NOT ( ACTIVE-DRIVE-TRUCK ?TRUCK0 ?LOCATION1 ?LOCATION2 ?DRIVER3 ) )
		( WHEN
			( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 )
			( AND
				( NOT ( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 ) )
				( COUNT0-DRIVING ?DRIVER3 ?TRUCK0 )
			)
		)
		( WHEN
			( COUNT2-DRIVING ?DRIVER3 ?TRUCK0 )
			( AND
				( NOT ( COUNT2-DRIVING ?DRIVER3 ?TRUCK0 ) )
				( COUNT1-DRIVING ?DRIVER3 ?TRUCK0 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-WALK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?DRIVER0 ?LOCATION1 )
		( PATH ?LOCATION1 ?LOCATION2 )
		( NOT ( ACTIVE-WALK ?DRIVER0 ?LOCATION1 ?LOCATION2 ) )
		( NOT ( STACK2 ) )
		( COUNT0-AT ?DRIVER0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( AT ?DRIVER0 ?LOCATION1 ) )
		( ACTIVE-WALK ?DRIVER0 ?LOCATION1 ?LOCATION2 )
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 200000 )
	)
)
( :ACTION END-WALK
  :PARAMETERS ( ?DRIVER0 - DRIVER ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( ACTIVE-WALK ?DRIVER0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( AT ?DRIVER0 ?LOCATION2 )
		( NOT ( ACTIVE-WALK ?DRIVER0 ?LOCATION1 ?LOCATION2 ) )
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
)
