( DEFINE ( DOMAIN PAPERCASE )
( :REQUIREMENTS :ACTION-COSTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	LOCATION - OBJECT
	AGENT - OBJECT
	HOLDER - OBJECT
	PART - OBJECT
	CABINET - OBJECT
	PATH - LOCATION
	RACK - LOCATION
)
( :PREDICATES
	( NEIGHBOR ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( BELONG ?AGENT0 - AGENT ?HOLDER1 - HOLDER )
	( HAVE ?CABINET0 - CABINET ?HOLDER1 - HOLDER )
	( AT ?AGENT0 - AGENT ?PATH1 - PATH )
	( FIXAT ?CABINET0 - CABINET ?PATH1 - PATH )
	( OCCUPIED ?PATH0 - PATH )
	( FREE ?HOLDER0 - HOLDER )
	( LOCATE ?PART0 - PART ?RACK1 - RACK )
	( ON ?PART0 - PART ?HOLDER1 - HOLDER )
	( EMPTYSTACK )
	( STACK1 )
	( STACK2 )
	( ACTIVE-MOVE ?AGENT0 - AGENT ?PATH1 - PATH ?PATH2 - PATH )
	( ACTIVE-PICK ?AGENT0 - AGENT ?PART1 - PART ?PATH2 - PATH ?RACK3 - RACK ?HOLDER4 - HOLDER )
	( ACTIVE-PLACE ?AGENT0 - AGENT ?CABINET1 - CABINET ?PATH2 - PATH ?PATH3 - PATH ?PART4 - PART ?HOLDER5 - HOLDER ?HOLDER6 - HOLDER )
	( COUNT0-AT ?AGENT0 - AGENT ?PATH1 - PATH )
	( COUNT1-AT ?AGENT0 - AGENT ?PATH1 - PATH )
	( COUNT2-AT ?AGENT0 - AGENT ?PATH1 - PATH )
)
( :FUNCTIONS
	( TOTAL-COST )
)
( :ACTION START-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?PATH1 - PATH ?PATH2 - PATH )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?PATH1 )
		( NOT ( OCCUPIED ?PATH2 ) )
		( NEIGHBOR ?PATH1 ?PATH2 )
		( NOT ( ACTIVE-MOVE ?AGENT0 ?PATH1 ?PATH2 ) )
		( NOT ( STACK2 ) )
		( COUNT0-AT ?AGENT0 ?PATH1 )
	)
  :EFFECT
	( AND
		( NOT ( OCCUPIED ?PATH1 ) )
		( NOT ( AT ?AGENT0 ?PATH1 ) )
		( ACTIVE-MOVE ?AGENT0 ?PATH1 ?PATH2 )
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 20000 )
	)
)
( :ACTION END-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?PATH1 - PATH ?PATH2 - PATH )
  :PRECONDITION
	( AND
		( NEIGHBOR ?PATH1 ?PATH2 )
		( ACTIVE-MOVE ?AGENT0 ?PATH1 ?PATH2 )
	)
  :EFFECT
	( AND
		( OCCUPIED ?PATH2 )
		( AT ?AGENT0 ?PATH2 )
		( NOT ( ACTIVE-MOVE ?AGENT0 ?PATH1 ?PATH2 ) )
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-PICK
  :PARAMETERS ( ?AGENT0 - AGENT ?PART1 - PART ?PATH2 - PATH ?RACK3 - RACK ?HOLDER4 - HOLDER )
  :PRECONDITION
	( AND
		( LOCATE ?PART1 ?RACK3 )
		( FREE ?HOLDER4 )
		( AT ?AGENT0 ?PATH2 )
		( NEIGHBOR ?PATH2 ?RACK3 )
		( BELONG ?AGENT0 ?HOLDER4 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?PART1 ?PATH2 ?RACK3 ?HOLDER4 ) )
		( NOT ( STACK2 ) )
	)
  :EFFECT
	( AND
		( NOT ( LOCATE ?PART1 ?RACK3 ) )
		( ACTIVE-PICK ?AGENT0 ?PART1 ?PATH2 ?RACK3 ?HOLDER4 )
		( WHEN
			( COUNT0-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT0-AT ?AGENT0 ?PATH2 ) )
				( COUNT1-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( COUNT1-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT1-AT ?AGENT0 ?PATH2 ) )
				( COUNT2-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 10000 )
	)
)
( :ACTION END-PICK
  :PARAMETERS ( ?AGENT0 - AGENT ?PART1 - PART ?PATH2 - PATH ?RACK3 - RACK ?HOLDER4 - HOLDER )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?PATH2 )
		( NEIGHBOR ?PATH2 ?RACK3 )
		( BELONG ?AGENT0 ?HOLDER4 )
		( ACTIVE-PICK ?AGENT0 ?PART1 ?PATH2 ?RACK3 ?HOLDER4 )
	)
  :EFFECT
	( AND
		( NOT ( FREE ?HOLDER4 ) )
		( ON ?PART1 ?HOLDER4 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?PART1 ?PATH2 ?RACK3 ?HOLDER4 ) )
		( WHEN
			( COUNT1-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT1-AT ?AGENT0 ?PATH2 ) )
				( COUNT0-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( COUNT2-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT2-AT ?AGENT0 ?PATH2 ) )
				( COUNT1-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
( :ACTION START-PLACE
  :PARAMETERS ( ?AGENT0 - AGENT ?CABINET1 - CABINET ?PATH2 - PATH ?PATH3 - PATH ?PART4 - PART ?HOLDER5 - HOLDER ?HOLDER6 - HOLDER )
  :PRECONDITION
	( AND
		( ON ?PART4 ?HOLDER5 )
		( FREE ?HOLDER6 )
		( AT ?AGENT0 ?PATH2 )
		( FIXAT ?CABINET1 ?PATH3 )
		( NEIGHBOR ?PATH2 ?PATH3 )
		( BELONG ?AGENT0 ?HOLDER5 )
		( HAVE ?CABINET1 ?HOLDER6 )
		( NOT ( ACTIVE-PLACE ?AGENT0 ?CABINET1 ?PATH2 ?PATH3 ?PART4 ?HOLDER5 ?HOLDER6 ) )
		( NOT ( STACK2 ) )
	)
  :EFFECT
	( AND
		( NOT ( ON ?PART4 ?HOLDER5 ) )
		( FREE ?HOLDER5 )
		( ACTIVE-PLACE ?AGENT0 ?CABINET1 ?PATH2 ?PATH3 ?PART4 ?HOLDER5 ?HOLDER6 )
		( WHEN
			( COUNT0-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT0-AT ?AGENT0 ?PATH2 ) )
				( COUNT1-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( COUNT1-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT1-AT ?AGENT0 ?PATH2 ) )
				( COUNT2-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( EMPTYSTACK )
			( AND
				( NOT ( EMPTYSTACK ) )
				( STACK1 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( STACK2 )
			)
		)
		( INCREASE ( TOTAL-COST ) 10000 )
	)
)
( :ACTION END-PLACE
  :PARAMETERS ( ?AGENT0 - AGENT ?CABINET1 - CABINET ?PATH2 - PATH ?PATH3 - PATH ?PART4 - PART ?HOLDER5 - HOLDER ?HOLDER6 - HOLDER )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?PATH2 )
		( FIXAT ?CABINET1 ?PATH3 )
		( NEIGHBOR ?PATH2 ?PATH3 )
		( BELONG ?AGENT0 ?HOLDER5 )
		( HAVE ?CABINET1 ?HOLDER6 )
		( ACTIVE-PLACE ?AGENT0 ?CABINET1 ?PATH2 ?PATH3 ?PART4 ?HOLDER5 ?HOLDER6 )
	)
  :EFFECT
	( AND
		( ON ?PART4 ?HOLDER6 )
		( NOT ( FREE ?HOLDER6 ) )
		( NOT ( ACTIVE-PLACE ?AGENT0 ?CABINET1 ?PATH2 ?PATH3 ?PART4 ?HOLDER5 ?HOLDER6 ) )
		( WHEN
			( COUNT1-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT1-AT ?AGENT0 ?PATH2 ) )
				( COUNT0-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( COUNT2-AT ?AGENT0 ?PATH2 )
			( AND
				( NOT ( COUNT2-AT ?AGENT0 ?PATH2 ) )
				( COUNT1-AT ?AGENT0 ?PATH2 )
			)
		)
		( WHEN
			( STACK1 )
			( AND
				( NOT ( STACK1 ) )
				( EMPTYSTACK )
			)
		)
		( WHEN
			( STACK2 )
			( AND
				( NOT ( STACK2 ) )
				( STACK1 )
			)
		)
		( INCREASE ( TOTAL-COST ) 1 )
	)
)
)
